"""add glb mesh fields

Revision ID: 3f4bca9f6df1
Revises: d2e3f4a5b6c7
Create Date: 2026-05-10 00:48:05.683253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f4bca9f6df1'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('glb_mesh_path', sa.String(), nullable=True))
    op.add_column('clothing_items', sa.Column('mesh_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing_items', 'mesh_status')
    op.drop_column('clothing_items', 'glb_mesh_path')
    # ### end Alembic commands ###
