"""Remove raw_image_path

Revision ID: baf1c8f5d6f4
Revises: 5579d0eabf99
Create Date: 2026-04-26 16:01:31.750443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf1c8f5d6f4'
down_revision: Union[str, None] = '5579d0eabf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing_items', 'raw_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('raw_image_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
